apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readconfigmaps
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readconfigmaps
  namespace: default
subjects:
- kind: ServiceAccount
  name: test-controller
  namespace: default
roleRef:
  kind: ClusterRole 
  name: readconfigmaps
  apiGroup: rbac.authorization.k8s.io